kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vault-controller
  namespace: {{ .Values.Namespace | quote }}
  labels:
    app: vault-controller
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-controller
    spec:
      containers:
        - name: vault-controller
          image: {{ .Values.Image }}
          command:
            - /kube-vault-controller
            - --sync-period=1m
            - --namespace={{ .Values.WatchNamespace }}
          env:
            - name: VAULT_ADDR
              value: {{ .Values.VaultAddress | quote }}
            - name: VAULT_TOKEN
              value: {{ .Values.VaultToken | quote }}
